#
# You can build the container with 'drone exec' it will not push that container to the cisco ECH registry
#
pipeline:
  build:
    image: docker:17.05.0-ce-dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk update && apk add bash curl git
      - bash BUILD.sh

  # This should only happen when the master branch has been merged.  I will protect the master branch.
  publish:
    secrets: [ECH_PASS]
    image: docker:17.05.0-ce-dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - if [ -z "$ECH_PASS" ]; echo "Must define ECH_PASS"; exit 1; fi
      - docker login -u="tropo_operations+jenkins_tropo" -p="$ECH_PASS" containers.cisco.com
      - bash PUSH.sh
    when:
      branch: master
      event:  push

secrets:
  ECH_PASS:
    driver: vault
    driver_opts:
      path: secret/internal/CI/ECH
      key: pass

